# Explanations & Usage: https://github.com/Zazsona/DecorHeads/wiki/Plugin-Config

version: 2.4.0
plugin-enabled: true
crafting: true
drops: true
environmental-drops: true
learn-recipes-from-wiki: true
update-notifications: minor
head-meta-patcher: false
drop-types:
  mine: true
  brew: true
  smelt: true
  craft: true
  entity-death: true
  player-death: true
