# Explanations & Usage: https://github.com/Zazsona/DecorHeads/wiki/Plugin-Config

version: 2.1.0
plugin-enabled: true
crafting: true
drops: true
playerless-drop-events: true
learn-recipes-from-wiki: true
update-notifications: minor
drop-sources:
  mine-drop: true
  brew-drop: true
  smelt-drop: true
  craft-drop: true
  entity-death-drop: true
  player-death-drop: true
