Enabled: true
DropsEnabled: true
CraftingEnabled: true
DropPercentages:
  Beer: 5
  Books: 10
  Snowman: 1
  Apple: 2
  Blueberry: 1
  Coconut: 3
  OakLog: 2
  Dirt: 1
  Leaves: 2
  Melon: 2
  Pumpkin: 2
  Cactus: 2
  Sushi: 8
  Bread: 1
  Cookie: 3
  Cake: 15
  Burger: 1
  ChickenDinner: 1
  RedstoneBlock: 3
  Gravel: 2
  Cobblestone: 2
  OakCharacterExclamation: 1
  OakCharacterQuestion: 1
  OakCharacterLeft: 1
  OakCharacterRight: 1
  OakCharacterUp: 1
  OakCharacterDown: 1
