Enabled: true
DropsEnabled: true
CraftingEnabled: true
MobDropsEnabled: true
PlayerDropsEnabled: true
PlayersHeadsPvPOnly: false
#These drop percentages are valid between 0 and 100
#They can, however, be to two decimal places (E.g, 0.01)
DropPercentages:
  Beer: 1
  Books: 5
  SnowmanHead: 1
  Apple: 0.2
  Blueberry: 0.2
  Coconut: 3
  MiniOakLog: 0.05
  MiniDirt: 0.01
  MiniLeaves: 1
  MiniMelon: 0.01
  MiniPumpkin: 0.05
  MiniCactus: 1
  Sushi: 8
  Bread: 0.25
  Cookie: 1
  Cupcake: 15
  Burger: 0.5
  ChickenDinner: 0.5
  MiniRedstoneBlock: 0.05
  MiniGravel: 0.01
  MiniCobblestone: 0.01
  OakCharacterExclamation: 0.16
  OakCharacterQuestion: 0.16
  OakCharacterLeftArrow: 0.16
  OakCharacterRightArrow: 0.16
  OakCharacterUpArrow: 0.16
  OakCharacterDownArrow: 0.16
  Slimeball: 1
  FruitBasket: 0.01
  Chicken: 0.01
  Cow: 0.01
  Fox: 1
  Mooshroom: 2
  Ocelot: 1
  Pig: 0.01
  Sheep: 0.01
  Squid: 0.01
  Villager: 0.1
  WanderingTrader: 3
  Spider: 0.05
  CaveSpider: 0.03
  Enderman: 0.02
  ZombiePigman: 0.02
  IronGolem: 0.5
  Dolphin: 1
  Blaze: 0.5
  Creeper: 0.01
  Drowned: 0.5
  ElderGuardian: 10
  Ghast: 3
  Guardian: 1
  Husk: 0.5
  MagmaCube: 1
  Pillager: 0.01
  Skeleton: 0.01
  Slime: 1
  Stray: 0.5
  Vex: 1
  Witch: 1
  WitherSkeleton: 0.02
  Zombie: 0.01
  ZombieVillager: 2
  Sandcastle: 0.5
  SandBucket: 0.05
  Player: 2
