# Global plugin toggle
# Note: Disabling this may remove head crafting progression data for players
plugin-enabled: true
# Allow crafting of supported heads
# Note: Disabling this may remove head crafting progression data for players
crafting: true
# Allow heads to drop
drops: true
# Allow heads to drop without any involvement from players (e.g, drops from mobs burning to death).
# If you're disabling DropHeads for some roles, I recommend disabling this otherwise they will be able to exploit these methods to get heads.
playerless-drop-events: true
# Add recipes to the player's crafting book when viewed in the wiki command for easier reference when crafting
learn-recipes-from-wiki: true
# Allows heads to drop from the specified source types
drop-sources:
  mine-drop: true
  entity-death-drop: true
  player-death-drop: true
