name: DecorHeads
version: 2.0.0
author: Zazsona
main: com.zazsona.decorheads.Core
api-version: 1.16
commands:
   decorheads:
      aliases:
         - decorhead
      description: Help page
      usage: /DecorHeads
   dhwiki:
      aliases:
         - decorheadwiki
         - decorheadswiki
         - headswiki
         - headwiki
      description: Info & head details
      usage: /DHWiki [Function] [Args]
      permission: decorheads.wiki
   dhconfig:
      aliases:
         - decorheadsconfig
      description: Edit heads and config
      usage: /DHEditor [Function] [Args]
      permission: decorheads.config
   dhspawn:
      aliases:
         - spawnhead
         - headspawn
         - headspawner
         - summonhead
         - headsummon
         - headsummoner
      description: Spawn a decor or player head
      usage: /DHSpawn [Decor|Player] [Name] ||| /SpawnHead All
      permission: decorheads.spawnhead
permissions:
   decorheads.dropheads:
      description: Have player's actions drop heads
      default: true
   decorheads.craftheads:
      description: Allow player to craft/make heads
      default: true
   decorheads.wiki:
      description: Check head wiki
      default: true
   decorheads.spawnheads:
      description: Spawn heads via command
      default: op
      children:
         decorheads.wiki: true
   decorheads.config:
      description: Manage the plugin
      default: op
   decorheads.*:
      description: All DecorHeads permissions
      default: op
      children:
         decorheads.dropheads: true
         decorheads.craftheads: true
         decorheads.wiki: true
         decorheads.spawnhead: true
         decorheads.config: true