name: DecorHeads
version: 3.0.0
author: Zazsona
main: com.zazsona.decorheads.DecorHeadsPlugin
api-version: 1.18
commands:
   decorheads:
      aliases:
         - decorhead
      description: Help page
      usage: /DecorHeads
   dhwiki:
      aliases:
         - decorheadwiki
         - decorheadswiki
         - headswiki
         - headwiki
      description: Info & head details
      usage: /DHWiki [Function] [Args]
      permission: decorheads.wiki
   dhconfig:
      aliases:
         - decorheadsconfig
      description: Edit heads and config
      usage: /DHConfig [Function] [Args]
      permission: decorheads.config
   dhspawn:
      aliases:
         - spawnhead
         - headspawn
         - headspawner
         - summonhead
         - headsummon
         - headsummoner
      description: Spawn a head. You may specify Decor or Player if a name overlaps.
      usage: /DHSpawn (Decor)/(Player) [Name] OR /DHSpawn All
      permission: decorheads.spawnhead
permissions:
   decorheads.dropheads:
      description: Have player's actions drop heads
      default: true
   decorheads.craftheads:
      description: Allow player to craft/make heads
      default: true
   decorheads.wiki:
      description: Check head wiki
      default: true
   decorheads.spawnheads:
      description: Spawn heads via command
      default: op
      children:
         decorheads.wiki: true
   decorheads.config:
      description: Manage the plugin
      default: op
   decorheads.notifyupdates:
      description: Notifies the user if an update is available
      default: op
   decorheads.*:
      description: All DecorHeads permissions
      default: op
      children:
         decorheads.dropheads: true
         decorheads.craftheads: true
         decorheads.wiki: true
         decorheads.spawnhead: true
         decorheads.config: true
         decorheads.notifyupdates: true