name: DecorHeads
version: 1.5.1
author: Zazsona
main: com.zazsona.decorheads.Core
api-version: 1.16
commands:
   DecorHeads:
      description: DecorHeads master command
      usage: /DecorHeads [Function] [Args]
permissions:
   DecorHeads.HeadDrop:
      description: Allows heads to drop for this player
      default: true
   DecorHeads.CraftHead:
      description: Allows heads to be crafted by this player
      default: true
   DecorHeads.CheckHead:
      description: Check head drop rates
      default: true
   DecorHeads.SummonHead:
      description: Allows players to get a head via command
      default: op
      children:
         DecorHeads.CheckHead: true
   DecorHeads.Admin:
      description: Manage the plugin
      default: op
      children:
         DecorHeads.SummonHead: true
         DecorHeads.CheckHead: true