name: DecorHeads
version: 1.6.0
author: Zazsona
main: com.zazsona.decorheads.Core
api-version: 1.16
commands:
   decorheads:
      aliases:
         - decorhead
      description: Help page
      usage: /DecorHeads
   dhwiki:
      aliases:
         - decorheadwiki
         - decorheadswiki
         - headswiki
         - headwiki
      description: Info & head details
      usage: /DHWiki [Function] [Args]
      permission: decorheads.wiki
   dhconfig:
      aliases:
         - decorheadsconfig
      description: Edit heads and config
      usage: /DHEditor [Function] [Args]
      permission: decorheads.config
   dhspawn:
      aliases:
         - spawnhead
         - headspawn
         - headspawner
         - summonhead
         - headsummon
         - headsummoner
      description: Spawn a decor or player head
      usage: /DHSpawn [Decor|Player] [Name] ||| /SpawnHead All
      permission: decorheads.spawnhead
permissions:
   decorheads.wiki:
      description: Check head wiki
      default: true
   decorheads.spawnhead:
      description: Spawn heads via command
      default: op
      children:
         decorheads.wiki: true
   decorheads.config:
      description: Manage the plugin
      default: op
      children:
         decorheads.wiki: true
   decorheads.*:
      description: All DecorHeads permissions
      default: op
      children:
         decorheads.wiki: true
         decorheads.spawnhead: true
         decorheads.config: true