name: DecorHeads
version: 1.6.0
author: Zazsona
main: com.zazsona.decorheads.Core
api-version: 1.16
commands:
   decorheads:
      aliases:
         - dh
         - decorhead
         - decorheadwiki
         - decorheadswiki
         - dhw
         - heads
         - headswiki
         - headwiki
      description: Info & head details
      usage: /DecorHeads [Function] [Args]
      permission: decorheads.wiki
   headeditor:
      aliases:
         - he
         - decorheadseditor
         - dhe
         - decorheadeditor
         - dheditor
      description: Edit heads and config
      usage: /HeadEditor [Function] [Args]
      permission: decorheads.admin
   spawnhead:
      aliases:
         - sh
         - headspawn
         - headspawner
         - summonhead
         - headsummon
         - headsummoner
      description: Spawn a decor or player head
      usage: /SpawnHead [Decor|Player] [Name] ||| /SpawnHead All
      permission: decorheads.summonhead
permissions:
   decorheads.wiki:
      description: Check head wiki
      default: true
   decorheads.summonhead:
      description: Spawn heads via command
      default: op
      children:
         decorheads.wiki: true
   decorheads.admin:
      description: Manage the plugin
      default: op
      children:
         decorheads.summonhead: true
   decorheads.*:
      description: All DecorHeads permissions
      default: op
      children:
         decorheads.admin: true